name = "SPlit"
uuid = "6b22f1a1-5f68-5715-9b23-279ae752cb98"
authors = ["Jongsu Kim <jongsukim8@gmail.com> and contributors"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
JuliaFormatter = "1"
julia = "1.10"
