name: pre-commit Update

on:
  schedule:
    - cron: "0 7 1/7 * *" # At 7:00 every 7 days
  workflow_dispatch:

jobs:
  pre-commit-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit's autoupdate
        run: |
          # ignore exit code
          pre-commit autoupdate || true
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "chore: :robot: pre-commit update"
          title: "[AUTO] pre-commit update"
          branch: auto-pre-commit-update
          delete-branch: true
          labels: chore
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
