name: Test

on:
  push:
    branches:
      - main
    tags: ["*"]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ReusableTest.yml
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      arch: ${{ matrix.arch }}
      allow_failure: ${{ matrix.allow_failure }}
      julia-version: ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "lts"
          - "pre"
          - "1"
        os:
          - ubuntu-latest
          - macos-13
          - windows-latest
        arch:
          - x64
        include:
          - os: macos-latest
            arch: aarch64

        allow_failure: [false]
