name: Test

on:
  push:
    branches:
      - main
    tags: ["*"]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ReusableTest.yml
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "lts"
          - "1"
          - "pre"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
